### ISSUE TITLE
Download source from repo

### ISSUE THREAD

**Issue by memsharded** [mathieu/conan-libjpeg#1]
Hi, nice work. It is possible to download the source code directly in the source() method, so no need to host it in your repo. Just an idea, it is ok as is too.

There is another libjpeg conanfile in conan.io by @Kaosumaru, maybe you want to have a look at it https://github.com/Kaosumaru/conan-libjpeg, colllaborate, or share ideas, so far I have used that one and works quite well.

**Comment by mathieu** [comment]
Yes I saw this afterward :-/

**Comment by mathieu** [comment]
Anyway that was just a practice project to understand the amount of work need to wrap an external library !

**Comment by memsharded** [comment]
Excellent, thanks for the info!
